package org.telegram.messenger.novagram.update;

import android.app.Activity;
import android.content.Context;
import android.content.SharedPreferences;

import org.telegram.messenger.AndroidUtilities;
import org.telegram.messenger.ApplicationLoader;
import org.telegram.messenger.FileLog;
import org.telegram.messenger.SharedConfig;
import org.telegram.messenger.Utilities;
import org.telegram.messenger.novagram.net.NovaDoh;
import org.telegram.messenger.novagram.net.NovaHttps;
import org.telegram.messenger.novagram.privacy.NovaDecoyState;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.URL;
import java.security.MessageDigest;
import java.util.ArrayList;

import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLSocket;

import org.json.JSONObject;

/**
 * Asks GitHub for the project's latest release and installs it if it is newer.
 *
 * <p>This is the only network request NovaGram makes outside Telegram, so it
 * is a setting rather than a fact of life, and it never runs while the decoy
 * is on: the decoy promises the process opens no sockets, and a request to
 * GitHub would break that promise in the most traceable way there is.</p>
 *
 * <p>One NovaGram release covers both platforms, and its tag carries both base
 * versions: {@code v<desktop>/<android>}. Each client compares only its own
 * half, which is what makes an Android-only release invisible to the desktop
 * and the other way round: if the number for this platform did not move, there
 * is nothing to install here even though the release is new.</p>
 *
 * <p>The downloaded package is checked against the digest GitHub publishes for
 * the asset before it is offered for installation. Installing over the existing
 * keeps application data: Android replaces the code and leaves the data
 * directory alone as long as the signing key is the same one.</p>
 */
public final class NovaUpdateChecker {
    public static final String PROJECT_URL = "https://github.com/confeden/Novagram";

    /**
     * Both halves of the joint release tag. Only the Android half can be read
     * from the package, so the whole tag has to be written down here and bumped
     * together with the bases.
     */
    public static final String RELEASE_TAG = "v7.1.3/12.10.1.1";

    /**
     * {@code /releases/latest} skips drafts and prereleases, which is exactly
     * what is wanted: a release being prepared must not be offered to anyone.
     *
     * <p>This replaced a hand-published JSON manifest in another repository.
     * The manifest had to be regenerated by a workflow after every release, so
     * until that ran the clients honestly reported "you have the latest
     * version" while a newer one was already on the Releases page. Reading the
     * release itself removes the step and the window in which it is wrong. The
     * desktop half has always done it this way.</p>
     */
    private static final String RELEASES_URL =
            "https://api.github.com/repos/confeden/Novagram/releases/latest";
    private static final String DOWNLOAD_PREFIX = PROJECT_URL + "/releases/download/";

    private static final String PREFERENCES = "novagram_update";
    private static final String KEY_ENABLED = "enabled";
    private static final String KEY_LAST_CHECK = "lastCheck";

    private static final long PERIOD_MS = 8L * 60L * 60L * 1000L;
    /**
     * A release object carries its whole description, so it is bigger than the
     * manifest this replaced. 256 KB is far above anything the project writes
     * and still small enough that a wrong answer cannot be used to make the
     * client read for a long time.
     */
    private static final int MAX_RELEASE_BYTES = 256 * 1024;
    private static final int MAX_PACKAGE_BYTES = 512 * 1024 * 1024;
    private static final int TIMEOUT_MS = 20 * 1000;

    /**
     * The same twenty seconds as the release check. A long timeout is the wrong
     * tool: it makes a broken transfer sit there looking alive. What makes a
     * download survive a connection that breaks every few megabytes is keeping
     * the bytes and continuing from them.
     */
    private static final int DOWNLOAD_TIMEOUT_MS = 20 * 1000;

    /**
     * How many times a download may continue by itself after breaking. Only
     * attempts that actually moved forward count, so this bounds pieces, not
     * retries of nothing.
     */
    private static final int MAX_DOWNLOAD_ATTEMPTS = 40;

    public enum State {
        IDLE,
        CHECKING,
        UP_TO_DATE,
        FOUND,
        DOWNLOADING,
        READY,
        FAILED,
    }

    /** The release GitHub reports as the latest one, reduced to what is used. */
    public static final class Release {
        public final String version;
        public final String url;
        public final String sha256;
        public final String releaseUrl;
        /** Zero when the asset carries no size; then no size is shown. */
        public final long size;

        Release(String version, String url, String sha256, String releaseUrl, long size) {
            this.version = version;
            this.url = url;
            this.sha256 = sha256;
            this.releaseUrl = releaseUrl;
            this.size = size;
        }
    }

    public interface Listener {
        void onNovaUpdateStateChanged();
    }

    private static final Object LOCK = new Object();
    private static final ArrayList<Listener> listeners = new ArrayList<>();

    private static volatile State state = State.IDLE;
    private static volatile Release release;
    private static volatile int progress;
    private static volatile File downloaded;
    private static volatile boolean busy;
    private static volatile boolean cancelRequested;

    /** The connection a download is reading from, so cancel() can close it. */
    private static volatile HttpURLConnection active;

    /** The same, for the path that opens its own socket. */
    private static volatile java.net.Socket activeSocket;

    /**
     * What earlier attempts of the current release managed to fetch. Kept so a
     * download that broke near the end continues instead of starting over: on
     * the kind of connection this fork is used over, fifty megabytes in one
     * unbroken run is the exception, not the rule.
     */
    private static volatile byte[] partial;
    private static volatile String partialVersion;

    /** Whether the last answer was a 206, i.e. only the tail that was asked for. */
    private static volatile boolean lastPartial;

    /** Consecutive automatic continuations of the current download. */
    private static volatile int attempts;

    /** Not an error: told apart from a real failure by its own type. */
    private static final class Cancelled extends Exception {
    }

    private NovaUpdateChecker() {
    }

    /**
     * The Telegram Android this build is based on, taken from the package
     * itself rather than from a constant: a constant would be one more thing
     * that can silently disagree with what was actually shipped.
     */
    public static String currentVersion() {
        try {
            Context context = ApplicationLoader.applicationContext;
            return context.getPackageManager()
                    .getPackageInfo(context.getPackageName(), 0).versionName;
        } catch (Throwable e) {
            FileLog.e(e);
            return "";
        }
    }

    /** Page of the release this build came from, with the list of changes. */
    public static String releaseUrl() {
        // The separator is escaped: a tag with a slash in it is a valid tag,
        // but a slash left raw in the path would be read as another segment.
        return PROJECT_URL + "/releases/tag/" + RELEASE_TAG.replace("/", "%2F");
    }

    // region state

    public static State getState() {
        return state;
    }

    public static Release getRelease() {
        return release;
    }

    public static int getProgress() {
        return progress;
    }

    public static void addListener(Listener listener) {
        synchronized (LOCK) {
            if (!listeners.contains(listener)) {
                listeners.add(listener);
            }
        }
    }

    public static void removeListener(Listener listener) {
        synchronized (LOCK) {
            listeners.remove(listener);
        }
    }

    private static void setState(State value) {
        state = value;
        // The list is read again inside the posted runnable, not snapshotted
        // here. runOnUIThread always posts, so a listener that unregistered in
        // between - a settings screen closed while a download reports its
        // percent a hundred times - would otherwise still be called, on a
        // destroyed fragment whose context is already gone.
        AndroidUtilities.runOnUIThread(() -> {
            final ArrayList<Listener> current;
            synchronized (LOCK) {
                current = new ArrayList<>(listeners);
            }
            for (Listener listener : current) {
                listener.onNovaUpdateStateChanged();
            }
        });
    }

    // endregion

    public static boolean isEnabled(Context context) {
        if (context == null || NovaDecoyState.isActive(context)) {
            return false;
        }
        return preferences(context).getBoolean(KEY_ENABLED, true);
    }

    public static void setEnabled(Context context, boolean enabled) {
        if (context == null) {
            return;
        }
        preferences(context).edit().putBoolean(KEY_ENABLED, enabled).apply();
        if (enabled) {
            checkNow();
        } else {
            stop();
        }
    }

    /**
     * Forgets the release that was found and stops a download in progress. The
     * bar at the bottom of the chat list is drawn from the state, so without
     * this a release found before the switch was turned off would go on
     * offering itself — and its button would still reach GitHub — from a client
     * that was told not to look. The desktop half does exactly the same.
     */
    public static void stop() {
        // Raised only while something is actually in flight. Raised
        // unconditionally it would latch: nothing lowers it except the start of
        // the next download, and the release read tests the same flag, so the
        // next check would be thrown away and the client would stop looking
        // for good.
        if (busy) {
            cancelRequested = true;
        }
        // Half a downloaded package goes with it: the user asked this to stop,
        // not to be remembered.
        partial = null;
        partialVersion = null;
        attempts = 0;
        release = null;
        downloaded = null;
        progress = 0;
        setState(State.IDLE);
    }

    /**
     * Called once from {@code ApplicationLoader.onCreate}. Checks only when the
     * period has really elapsed, so restarting the application ten times in a
     * row does not produce ten requests.
     */
    public static void start() {
        Context context = ApplicationLoader.applicationContext;
        if (!isEnabled(context)) {
            return;
        }
        long last = preferences(context).getLong(KEY_LAST_CHECK, 0L);
        long now = System.currentTimeMillis();
        // A clock moved backwards would otherwise postpone the check for as
        // long as the user set the clock back by.
        if (last > now || now - last >= PERIOD_MS) {
            checkNow();
        }
    }

    public static void checkNow() {
        Context context = ApplicationLoader.applicationContext;
        if (!isEnabled(context) || busy) {
            return;
        }
        busy = true;
        cancelRequested = false;
        setState(State.CHECKING);
        Utilities.globalQueue.postRunnable(() -> {
            try {
                byte[] body = read(RELEASES_URL, MAX_RELEASE_BYTES, null);
                applyRelease(context, new String(body, "UTF-8"));
            } catch (Throwable e) {
                if (cancelRequested) {
                    // The switch was turned off while the answer was on its
                    // way. stop() has already set the state.
                    setState(State.IDLE);
                } else {
                    FileLog.e(e);
                    // A check that failed must not leave behind the release an
                    // earlier one found: the bar and the settings row tell a
                    // failed download from a failed check by whether a release
                    // is known, and a stale one would label the wrong thing.
                    release = null;
                    setState(State.FAILED);
                }
            } finally {
                cancelRequested = false;
                busy = false;
            }
        });
    }

    /**
     * The half of the tag that belongs to this platform. A tag names both bases
     * - "v7.1.2/12.10.1" - because one release covers two clients, and each of
     * them compares only its own half. Android is the half after the slash.
     */
    private static String versionFromTag(String tag) {
        String trimmed = tag == null ? "" : tag.trim();
        if (trimmed.startsWith("v")) {
            trimmed = trimmed.substring(1);
        }
        int slash = trimmed.indexOf('/');
        return slash < 0 ? trimmed : trimmed.substring(slash + 1);
    }

    private static void applyRelease(Context context, String body) throws Exception {
        JSONObject object = new JSONObject(body);
        String version = versionFromTag(object.optString("tag_name", ""));
        String releaseUrl = object.optString("html_url", "");
        String url = "";
        String sha256 = "";
        long size = 0L;
        // The asset is found by what it is, not by its exact name: a rename in
        // the packaging script must not silently stop every client updating.
        org.json.JSONArray assets = object.optJSONArray("assets");
        for (int i = 0; assets != null && i < assets.length(); i++) {
            JSONObject asset = assets.optJSONObject(i);
            if (asset == null) {
                continue;
            }
            String name = asset.optString("name", "");
            if (!name.toLowerCase().endsWith(".apk")) {
                continue;
            }
            url = asset.optString("browser_download_url", "");
            size = asset.optLong("size", 0L);
            // GitHub gives it as "sha256:<hex>". Anything else is not a digest
            // this code knows how to check, and a check that silently passes is
            // worse than none - so an unknown algorithm leaves the field empty
            // and download() then refuses to install.
            String digest = asset.optString("digest", "").toLowerCase();
            if (digest.startsWith("sha256:")) {
                sha256 = digest.substring(7);
            }
            break;
        }
        if (version.length() == 0) {
            release = null;
            setState(State.FAILED);
            return;
        }
        // The answer may only ever point back into the project it belongs to.
        if (releaseUrl.length() > 0 && !releaseUrl.startsWith(PROJECT_URL)) {
            release = null;
            setState(State.FAILED);
            return;
        }
        if (url.length() > 0 && !url.startsWith(DOWNLOAD_PREFIX)) {
            release = null;
            setState(State.FAILED);
            return;
        }

        preferences(context).edit()
                .putLong(KEY_LAST_CHECK, System.currentTimeMillis())
                .apply();

        String current = currentVersion();
        if (current.length() == 0 || compareVersions(version, current) <= 0) {
            release = null;
            setState(State.UP_TO_DATE);
        } else {
            release = new Release(version, url, sha256, releaseUrl, size);
            setState(State.FOUND);
        }
    }

    public static void download() {
        Release target = release;
        if (busy || target == null || target.url.length() == 0) {
            return;
        }
        if (target.sha256.length() != 64) {
            // A package that cannot be checked is not installed. Publishing a
            // release without the digest is a mistake worth failing on.
            setState(State.FAILED);
            return;
        }
        busy = true;
        cancelRequested = false;
        if (!target.version.equals(partialVersion)) {
            partial = null;
            partialVersion = target.version;
        }
        progress = 0;
        setState(State.DOWNLOADING);
        Utilities.globalQueue.postRunnable(() -> {
            boolean again = false;
            final int held = (partial != null) ? partial.length : 0;
            final java.io.ByteArrayOutputStream sink = new java.io.ByteArrayOutputStream();
            try {
                read(target.url, MAX_PACKAGE_BYTES, value -> {
                    progress = value;
                    setState(State.DOWNLOADING);
                }, held, DOWNLOAD_TIMEOUT_MS, sink);
                keep(sink);
                if (!hexDigest(partial).equals(target.sha256)) {
                    // Not the release it claims to be: a truncated tail, a
                    // mixed-up resume, a changed file. Keeping it would make
                    // every later attempt continue from the same wrong bytes.
                    partial = null;
                    attempts = 0;
                    setState(State.FAILED);
                    return;
                }
                File file = store(partial, target.version);
                if (file == null) {
                    attempts = 0;
                    setState(State.FAILED);
                    return;
                }
                downloaded = file;
                partial = null;
                partialVersion = null;
                attempts = 0;
                setState(State.READY);
            } catch (Throwable e) {
                keep(sink);
                if (cancelRequested) {
                    // Asked for, not broken. What arrived is kept, so pressing
                    // the button again asks for the rest of it. release is null
                    // when the stop came from the switch, and then there is
                    // nothing to go back to.
                    setState(release != null ? State.FOUND : State.IDLE);
                } else if (partial != null
                        && partial.length > held
                        && ++attempts < MAX_DOWNLOAD_ATTEMPTS) {
                    // The attempt moved forward, so it is worth repeating at
                    // once: on a connection that breaks every few megabytes the
                    // file only ever arrives in pieces, and asking the user to
                    // press the button forty times is not offering the feature.
                    again = true;
                } else {
                    FileLog.e(e);
                    attempts = 0;
                    setState(State.FAILED);
                }
            } finally {
                cancelRequested = false;
                busy = false;
            }
            if (again) {
                download();
            }
        });
    }

    /** Appends what an attempt delivered, or replaces when it was not a tail. */
    private static void keep(java.io.ByteArrayOutputStream sink) {
        final byte[] got = sink.toByteArray();
        if (got.length == 0) {
            return;
        }
        partial = (lastPartial && partial != null) ? concat(partial, got) : got;
    }

    /**
     * Stops a download in progress. The official update bar offers this while
     * downloading, and a client that cannot stop a download it started on a
     * metered connection is worse than one that never offered it.
     */
    public static void cancel() {
        if (state == State.DOWNLOADING) {
            cancelRequested = true;
            // The flag alone is only read between two reads from the socket. A
            // stalled connection would sit in read() until the twenty second
            // timeout, and the user would watch a "stopping" that does not
            // stop. Closing the connection makes the blocked read return now.
            final HttpURLConnection connection = active;
            if (connection != null) {
                // On its own thread: the download holds the global queue, so
                // anything posted there would wait for the very read it is
                // meant to unblock, and disconnect() may touch the socket,
                // which the main thread is not allowed to do.
                new Thread(connection::disconnect).start();
            }
            final java.net.Socket socket = activeSocket;
            if (socket != null) {
                new Thread(() -> NovaHttps.close(socket)).start();
            }
        }
    }

    /** The verified package waiting to be installed, or null. */
    public static File getDownloadedFile() {
        return downloaded;
    }

    /**
     * Hands the package to the system installer. Nothing is installed behind
     * the user's back: this opens the ordinary Android install screen, and
     * {@code openForView} already asks for the install permission when the
     * system has not granted it yet.
     */
    public static void install(Activity activity) {
        File file = downloaded;
        if (activity == null || file == null || !file.exists()) {
            return;
        }
        AndroidUtilities.openForView(
                file,
                file.getName(),
                "application/vnd.android.package-archive",
                activity,
                null,
                false);
    }

    // region plumbing

    private interface Progress {
        void report(int percent);
    }

    /**
     * The proxy the user chose for Telegram, whenever it is one a plain HTTPS
     * request can use. Without this the update check goes out directly while
     * everything else in the client goes through the proxy — and where the
     * GitHub is blocked, that is the difference between an update the
     * user can install and one they never hear about.
     *
     * <p>Honest boundary, the same one the desktop half carries: an MTProto
     * proxy cannot carry this request at all. It speaks Telegram's protocol
     * and nothing else, so a client whose only way out is an MTProto proxy
     * will fail the check — visibly, on the twenty second timeout.</p>
     */
    private static Proxy proxy() {
        // One policy for everything that leaves the Telegram network, resolver
        // included — see NovaDoh.proxyFor(). It also refuses a proxy whose own
        // name is not resolved yet, which this used to hand straight to
        // InetSocketAddress, and that constructor resolves through the system.
        return NovaDoh.proxyFor();
    }

    private static byte[] read(String url, int limit, Progress progress) throws Exception {
        java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
        read(url, limit, progress, 0, TIMEOUT_MS, out);
        return out.toByteArray();
    }

    /**
     * Writes into a sink the caller owns rather than returning bytes, so that
     * a transfer which breaks halfway leaves what it managed to deliver in the
     * caller's hands. Returning them only on success is why resuming did not
     * work: everything already received was thrown away with the exception.
     */
    private static void read(
            String url,
            int limit,
            Progress progress,
            int resumeFrom,
            int timeout,
            java.io.ByteArrayOutputStream out) throws Exception {
        lastPartial = false;
        final Proxy proxy = proxy();
        if (proxy == Proxy.NO_PROXY) {
            // No proxy, so this machine is the one that would have to look the
            // name up — and it is not going to. See readResolved().
            readResolved(url, limit, progress, resumeFrom, timeout, out, 0);
            return;
        }
        // With a proxy the name is resolved by the proxy, and nothing is looked
        // up on this device at all — which is what the promise asks for, and is
        // stricter than doing it ourselves rather than weaker. The code below
        // is therefore left exactly as it was: in a network where a proxy is
        // set, the new path does not run, and a working download does not get
        // to be the place a new HTTP client is tried out for the first time.
        HttpURLConnection connection =
                (HttpURLConnection) new URL(url).openConnection(proxy);
        try {
            if (!(connection instanceof HttpsURLConnection)) {
                // Plain HTTP would let anyone on the path choose what NovaGram
                // installs. The release answer is checked the same way.
                throw new IllegalArgumentException("only https is accepted");
            }
            connection.setConnectTimeout(timeout);
            connection.setReadTimeout(timeout);
            if (resumeFrom > 0) {
                // The asset host answers 206 and sends only the tail; one that
                // cannot answers 200 with the whole file, and the caller
                // replaces what it held. The digest decides either way.
                connection.setRequestProperty("Range", "bytes=" + resumeFrom + "-");
            }
            connection.setInstanceFollowRedirects(true);
            connection.setRequestProperty("User-Agent", "NovaGram");
            active = connection;
            final int code = connection.getResponseCode();
            if (code != HttpURLConnection.HTTP_OK
                    && code != HttpURLConnection.HTTP_PARTIAL) {
                throw new IllegalStateException("http " + code);
            }
            lastPartial = (code == HttpURLConnection.HTTP_PARTIAL);
            // Only what is already held counts towards the shown percentage
            // when the server sent just the tail; when it ignored the Range and
            // sent everything, the held bytes are about to be replaced.
            final long base = lastPartial ? resumeFrom : 0;
            final int total = connection.getContentLength();
            final long full = (total > 0) ? (base + total) : 0;
            InputStream stream = connection.getInputStream();
            byte[] buffer = new byte[64 * 1024];
            int read;
            long done = 0;
            int reported = -1;
            while ((read = stream.read(buffer)) > 0) {
                if (cancelRequested) {
                    throw new Cancelled();
                }
                done += read;
                if (base + done > limit) {
                    throw new IllegalStateException("answer is too large");
                }
                out.write(buffer, 0, read);
                if (progress != null && full > 0) {
                    int percent = (int) (((base + done) * 100L) / full);
                    if (percent != reported) {
                        reported = percent;
                        progress.report(percent);
                    }
                }
            }
        } finally {
            active = null;
            connection.disconnect();
        }
    }

    /**
     * The same read, with the name turned into an address here rather than by
     * the system.
     *
     * <p>Redirects are followed by hand on purpose. GitHub sends the download
     * on to another host, and letting the stack follow a {@code Location} by
     * name would put the system resolver back into the middle of the one
     * request this fork promises to keep out of it. Every hop is resolved
     * again, every hop has to be https, and there are at most five.</p>
     *
     * <p>What a redirect carries in its body is not the file, so the partial is
     * untouched by one and the next hop simply asks for the same range.</p>
     */
    private static void readResolved(
            String url,
            int limit,
            Progress progress,
            int resumeFrom,
            int timeout,
            java.io.ByteArrayOutputStream out,
            int hop) throws Exception {
        if (hop > 5) {
            throw new IllegalStateException("too many redirects");
        }
        java.net.URI uri = new java.net.URI(url);
        if (!"https".equalsIgnoreCase(uri.getScheme())) {
            // Plain HTTP would let anyone on the path choose what NovaGram
            // installs. The release answer is checked the same way.
            throw new IllegalArgumentException("only https is accepted");
        }
        final String host = uri.getHost();
        NovaDoh.Answer answer = NovaDoh.resolve(host, NovaDoh.TYPE_A);
        if (answer.isEmpty()) {
            // No fall-back to the system resolver, by design: a name that
            // quietly resolved through the system is the leak this replaces.
            throw new IllegalStateException("could not resolve " + host + " over secure DNS");
        }
        String path = uri.getRawPath();
        if (path == null || path.length() == 0) {
            path = "/";
        }
        if (uri.getRawQuery() != null) {
            path = path + "?" + uri.getRawQuery();
        }

        SSLSocket socket = null;
        try {
            socket = NovaHttps.connect(host, answer.first(), Proxy.NO_PROXY, timeout);
            activeSocket = socket;
            java.util.Map<String, String> headers = NovaHttps.headers();
            headers.put("User-Agent", "NovaGram");
            if (resumeFrom > 0) {
                // The asset host answers 206 and sends only the tail; one that
                // cannot answers 200 with the whole file, and the caller
                // replaces what it held. The digest decides either way.
                headers.put("Range", "bytes=" + resumeFrom + "-");
            }
            OutputStream request = socket.getOutputStream();
            request.write(NovaHttps.head("GET", host, path, headers));
            request.flush();

            NovaHttps.Reader reader = NovaHttps.open(socket.getInputStream());
            final int code = reader.response.code;
            if (code >= 300 && code < 400 && reader.response.location != null) {
                final String next = uri.resolve(reader.response.location).toString();
                NovaHttps.close(socket);
                socket = null;
                activeSocket = null;
                readResolved(next, limit, progress, resumeFrom, timeout, out, hop + 1);
                return;
            }
            if (code != 200 && code != 206) {
                throw new IllegalStateException("http " + code);
            }
            lastPartial = (code == 206);
            // Only what is already held counts towards the shown percentage
            // when the server sent just the tail; when it ignored the Range and
            // sent everything, the held bytes are about to be replaced.
            final long base = lastPartial ? resumeFrom : 0;
            final int[] reported = new int[] { -1 };
            reader.drain(
                    out,
                    // What is already held counts towards the cap, exactly as
                    // it did before: the limit is on the file, not on one leg
                    // of fetching it.
                    Math.max(0, limit - base),
                    base,
                    (done, total) -> {
                        if (progress == null || total <= 0) {
                            return;
                        }
                        int percent = (int) ((done * 100L) / total);
                        if (percent != reported[0]) {
                            reported[0] = percent;
                            progress.report(percent);
                        }
                    },
                    () -> {
                        if (cancelRequested) {
                            throw new Cancelled();
                        }
                        return false;
                    });
        } finally {
            activeSocket = null;
            NovaHttps.close(socket);
        }
    }

    private static File store(byte[] body, String version) {
        // Under files/cache, which is the subtree the FileProvider of this
        // application already exposes; anywhere else the install intent would
        // be handed a URI the system refuses to open.
        File folder = new File(
                new File(ApplicationLoader.applicationContext.getFilesDir(), "cache"),
                "novagram_update");
        if (!folder.isDirectory() && !folder.mkdirs()) {
            return null;
        }
        for (File old : folder.listFiles() != null ? folder.listFiles() : new File[0]) {
            old.delete();
        }
        File file = new File(folder, "NovaGram-" + version + ".apk");
        OutputStream stream = null;
        try {
            stream = new FileOutputStream(file);
            stream.write(body);
            stream.flush();
            return file;
        } catch (Throwable e) {
            FileLog.e(e);
            return null;
        } finally {
            if (stream != null) {
                try {
                    stream.close();
                } catch (Throwable ignored) {
                }
            }
        }
    }

    private static byte[] concat(byte[] head, byte[] tail) {
        byte[] result = new byte[head.length + tail.length];
        System.arraycopy(head, 0, result, 0, head.length);
        System.arraycopy(tail, 0, result, head.length, tail.length);
        return result;
    }

    private static String hexDigest(byte[] body) throws Exception {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        byte[] hash = digest.digest(body);
        StringBuilder builder = new StringBuilder(hash.length * 2);
        for (byte value : hash) {
            builder.append(Character.forDigit((value >> 4) & 0xf, 16));
            builder.append(Character.forDigit(value & 0xf, 16));
        }
        return builder.toString();
    }

    /**
     * Negative when {@code a} is older than {@code b}, zero when they are the
     * same release, positive when {@code a} is newer. Missing components count
     * as zero, so "1.1" and "1.1.0" are one version.
     */
    public static int compareVersions(String a, String b) {
        String[] left = a.split("\\.");
        String[] right = b.split("\\.");
        int count = Math.max(left.length, right.length);
        for (int i = 0; i < count; i++) {
            int one = part(left, i);
            int two = part(right, i);
            if (one != two) {
                return one < two ? -1 : 1;
            }
        }
        return 0;
    }

    private static int part(String[] parts, int index) {
        if (index >= parts.length) {
            return 0;
        }
        try {
            return Integer.parseInt(parts[index].trim());
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private static SharedPreferences preferences(Context context) {
        return context.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE);
    }

    // endregion
}
